
create table META_DATABASES (
    USERNAME varchar(30) , 
    VERSION_NUMBER varchar(32) not null,
    TYPE_NAME varchar(15) not null, 
    CONNECTION_ID numeric(31) not null,
    CONNECTION_NAME varchar(30) not null,  
    CONNECTION_STRING varchar(200) not null,
    PASSWORD varchar(30) , 
    DESCRIPTION varchar(32000) , 
    DRIVER_NAME varchar(100) not null,
    DB_LINK_NAME varchar(128));  

--/***************************
--  META_COLLECTION_SETS
--/***************************
create table META_COLLECTION_SETS (
	COLLECTION_SET_ID numeric(31) not null,
	COLLECTION_SET_NAME varchar(128) not null,
	DESCRIPTION varchar(32000) ,
	VERSION_NUMBER varchar(32) not null,
	ENABLED_FLAG varchar(1) ,
	TYPE varchar(32) 
);

alter table META_COLLECTION_SETS
    add primary key (COLLECTION_SET_ID, VERSION_NUMBER);
       
--/***************************
--  META_COLLECTIONS
--/***************************
create table META_COLLECTIONS (
	COLLECTION_ID NUMERIC(38), 
	COLLECTION_NAME VARCHAR(128), 
	COLLECTION VARCHAR(200), 
	MAIL_ERROR_ADDR VARCHAR(100), 
	MAIL_FAIL_ADDR VARCHAR(100), 
	MAIL_BUG_ADDR VARCHAR(100), 
	MAX_ERRORS NUMERIC(38), 
	MAX_FK_ERRORS NUMERIC(38), 
	MAX_COL_LIMIT_ERRORS NUMERIC(38), 
	CHECK_FK_ERROR_FLAG VARCHAR(1), 
	CHECK_COL_LIMITS_FLAG VARCHAR(1), 
	LAST_TRANSFER_DATE DATETIME, 
	VERSION_NUMBER VARCHAR(32), 
	COLLECTION_SET_ID NUMERIC(38), 
	USE_BATCH_ID VARCHAR(1), 
	PRIORITY NUMERIC(3), 
	QUEUE_TIME_LIMIT NUMERIC(38), 
	ENABLED_FLAG VARCHAR(1), 
	SETTYPE VARCHAR(10), 
	FOLDABLE_FLAG VARCHAR(1), 
	MEASTYPE VARCHAR(30), 
	HOLD_FLAG VARCHAR(1), 
	SCHEDULING_INFO VARCHAR(2000)
);

alter table META_COLLECTIONS 
	add primary key (COLLECTION_NAME, COLLECTION_SET_ID, VERSION_NUMBER);

--/***************************
--  META_TRANSFER_ACTIONS
--/***************************
create table META_TRANSFER_ACTIONS (
	VERSION_NUMBER VARCHAR(32) not null, 
	TRANSFER_ACTION_ID numeric(31) not null, 
	COLLECTION_ID numeric(31) not null, 
	COLLECTION_SET_ID numeric(31) not null, 
	ACTION_TYPE VARCHAR(20) not null,	
	TRANSFER_ACTION_NAME VARCHAR(128) not null,	
	ORDER_BY_NO numeric(31) not null,	
	DESCRIPTION VARCHAR(32000),	
	WHERE_CLAUSE_01 VARCHAR(32000),	
	ACTION_CONTENTS_01 VARCHAR(32000), 
	ENABLED_FLAG VARCHAR(1) not null, 
	CONNECTION_ID numeric(31),	
	WHERE_CLAUSE_02 VARCHAR(32000),	
	WHERE_CLAUSE_03 VARCHAR(32000),	
	ACTION_CONTENTS_02 VARCHAR(32000), 
	ACTION_CONTENTS_03 VARCHAR(32000)
);
    
alter table META_TRANSFER_ACTIONS 
	add primary key (COLLECTION_ID, COLLECTION_SET_ID, TRANSFER_ACTION_ID, VERSION_NUMBER);
